### ISSUE TITLE
Csv export options not restricted based on user permissions

### ISSUE THREAD

**Issue by Ahsan0001** [thomst/django-admin-csvexport#10]
Users with only view access to one model can still export data for related models without having permissions to view them.

**Comment by thomst** [comment]
@Ahsan0001  Thank you for pointing to this issue. It will be fixed in the upcoming version: 3.0

**Comment by thomst** [comment]
> @Ahsan0001 Thank you for pointing to this issue. It will be fixed in the upcoming version: 3.0

Sorry. Fixed version is 2.1
